// import Footer from "@/components/Footer";
// import Header from "@/components/Header";
// import type { Metadata } from "next";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <div className="flex flex-col">
//       <Header />
//       <div className="flex">{children}</div>
//       <Footer />
//     </div>
//   );
// }

import Footer from "@/components/Footer";
import Header from "@/components/Header";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Product Details - Create Next App",
  description: "View detailed information about our products.",
};

export default function ProductLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-col min-h-screen text-sm">
      <Header />
      <div className="flex flex-1 justify-start items-start bg-[#effaf9] p-5">
        {children}
      </div>
      <Footer />
    </div>
  );
}

